#!/bin/zsh

# Configs
alias reload="source ~/.zshrc"
alias zshconfig="nano ~/.zshrc"
alias sshconfig="nano ~/.ssh/config"
alias tmuxconfig="nano ~/.tmux.conf.local"

# File system
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ll="ls -lsa"
alias md="mkdir -p"
alias rd="rmdir"
alias rgrep="grep -Hr"

### Git
alias gs="git status"
alias gst="git status"
alias ga="git add"
alias gp="git push"
alias gl="git pull origin"
alias gb="git branch "
alias gc="git commit "
alias gd="git diff"
alias gco="git checkout "
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias gsl="git stash list"
alias gsa="git stash apply"
alias gsp="git stash pop"

### NPM
alias nvp="npm version patch"
alias np="npm publish"

### Misc
alias dotf="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias whatsmyip="curl https://ipinfo.io/ip"
alias scanKeys='for key in $HOME/.ssh/*.pub; do ssh-keygen -l -f "${key}"; done | uniq'
alias ffs="sudo !!"
alias k=kubectl

### Specific to MacOS
if [[ `uname` == "Darwin" ]]; then
    alias flushDNS="sudo killall -HUP mDNSResponder;sudo kill mDNSResponderHelper;sudo dscacheutil -flushcache"
	alias syncTime="sudo sntp -sS time.euro.apple.com"
	alias mount_dev="mkdir -p ~/Media/dev.glimworks.se && sshfs -o idmap=user,noapplexattr,auto_cache,reconnect,defer_permissions,noappledouble,volname=dev.glimworks.se dev: ~/Media/dev.glimworks.se/"
	alias umount_dev="diskutil umount ~/Media/dev.glimworks.se"
fi